# Generated by Django 3.2.7 on 2022-06-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_hover',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
