# Generated by Django 3.2.7 on 2022-06-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_hover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('Sale', 'sale'), ('New', 'new'), ('Promotion', 'promotion')], max_length=10),
        ),
    ]
